# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8901d1461b592df4d78f829d7c90807e480c99b81e1ca9b35bd779e52634e4c6f96a94fe9bd94d74888d360322ba7de1cdc9b6175cc38a77517b40677d342694

test:
  secret_key_base: dd46c88c4174c33a683a0cb8009af021be076bcba0a831be8ed8d12c15683fd0820c2e4eacbee1ae7a8dfd56dfa3982c8ea5a28b0f83e6772f62ff3cdf7d83a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
